name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️ Build JAR
      - name: Build JAR with Maven
        run: mvn clean package

      # 4️ Build Docker image
      - name: Build Docker image
        run: docker build -t java-hello:latest .

      # 5️ Create kind Kubernetes cluster
      - name: Create kind cluster
        run: |
          kind create cluster --name kind

      # 6️ Load Docker image into kind cluster
      - name: Load image into kind
        run: |
          kind load docker-image java-hello:latest --name kind

      # 7️ Deploy application to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl get pods
          kubectl get services
